# Generated by Django 5.0.6 on 2024-07-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_remove_brands_vehicle'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='car',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='price',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brands'),
        ),
    ]
