# Generated by Django 5.0.6 on 2024-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicles_car_remove_vehicles_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
